config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :devices
  resources :directories
  resources :image_sliders
  resources :tags
  mount Ckeditor::Engine => '/ckeditor'

  root 'page#index'
  get 'dashboard' => "dashboard#index"

  get 'banners/remover' => 'banners#remover', as: :banners_remover
  get 'banners/article' => 'banners#article', as: :banners_article
  get 'redirect' => 'banners#counter', as: :banners_counter
  get 'send-report-banner' => 'banners#send_report_banner', as: :send_report_banner
  get 'banners/active' => 'banners#active', as: :banners_active
  get 'banners/trash' => 'banners#trash', as: :banners_trash
  resources :banners
  post 'banners/editbanner' => 'banners#editbanner', as: :banners_editbanner
  resources :galleries do
    collection { post :import }
    resources :images, :only => [:create, :destroy]
  end
  resources :videos
  resources :subscribes

  resources :sliders do
    put :sort, on: :collection
  end

  resources :users
  devise_for :users,
  path_names: {
    sign_in: 'digital/login',
    sign_out: 'digital/logout'
  }

  resources :writers do
    collection { post :import }
  end
  resources :contacts

  get 'tagged' => 'page#tagged', as: :tagged_article
  get '/city-updates', to: redirect('/updates', status: 301)
  get '/kids-family', to: redirect('/life/kids-family', status: 301)
  get '/lifestyle', to: redirect('/life', status: 301)
  get '/others', to: redirect('/people', status: 301)
  get '/our-contributors', to: redirect('/about', status: 301)
  get '/soapbox', to: redirect('/people/soapbox', status: 301)
  get '/magazine-issue/money-finance/brikcoin-a-eryptocurrency-for-the-value-of-the-absence-of-plastic', to: redirect('/magazine-issue/money-finance/brikcoin-a-cryptocurrency-for-the-value-of-the-absence-of-plastic', status: 301)
  get '/dining/foodies-corner/ultraviolet-by-paul-piret-multi-sensory-dining-at-its-best', to: redirect('/dining/foodies-corner/ultraviolet-by-paul-pairet-multi-sensory-dining-at-its-best', status: 301)
  get '/art-and-culture/arts/bartega-paint-sip-painting-under-influence', to: redirect('/art-and-culture/arts/bartega-studio-inspiring-creativity-through-social-painting', status: 301)
  get '/dining/culinary-talk/riana-bismaraks-favourite-restaurant', to: redirect('/dining/culinary-talk/5-top-jakarta-restaurants-in-riana-bismaraks-list', status: 301)
  get '/art-and-culture/arts/dedication-chairil-anwar', to: redirect('/art-and-culture/arts/bio-fantasy-melisa-sunjayas-dedication-to-chairil-anwar-bio-fantasy-melisa-sunjayas-dedication-to-chairil-now-jakarta', status: 301)
  get 'search' => 'page#search', as: :search
  get '/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get '/travel/archipelago-diaries/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get 'events/concerts'=> 'events#detail', as: :concerts_events
  get 'events/exhibition'=> 'events#detail', as: :exhibition_events
  get 'events/networking'=> 'events#detail', as: :networking_events
  get 'events/bazaar-and-festival'=> 'events#detail', as: :bazaar_festival_events
  get 'events/seminar-and-workshop'=> 'events#detail', as: :seminar_and_workshop_events
  get 'events/education'=> 'events#detail', as: :education_events
  get 'events/social'=> 'events#detail', as: :social_events
  get 'events/performance'=> 'events#detail', as: :performance_events
  get 'events/competition'=> 'events#detail', as: :competition_events
  get 'events/festive'=> 'events#detail', as: :festive_events
  get 'events/webinar'=> 'events#detail', as: :webinar_events

  get '/city-guides/kota-tua' => 'page#detail_area', as: :detail_area
  get 'latest-articles' => 'page#latest', as: :latest
  get '/list-event' => 'events#index', as: :list_event
  get '/list-article' => 'articles#index', as: :list_article
  get '/export-article' => 'articles#export', as: :export_article
  get '/list-subscriber' => 'subscribes#index', as: :list_subscriber
  get '/events' => 'page#events', as: :all_event

  get '/categories/:id/edit', to: 'categories#edit'
  get '/events/new', to: 'events#new'
  get '/events/:id', to: 'events#show', as: :dtl_event
  get '/events/:id/edit', to: 'events#edit'

  get '/city-guide' => 'categories#detail', as: :city_guide
  get '/photo-stories' => 'page#photos', as: :photos
  get 'dining' => 'categories#detail', as: :dining
  get 'people' => 'categories#detail', as: :people
  get 'art-and-culture' => 'categories#detail', as: :art_and_culture
  get 'life' => 'categories#detail', as: :life
  get 'updates' => 'categories#detail', as: :updates
  get 'events' => 'categories#detail', as: :nearest_event
  get 'business' => 'categories#detail', as: :business
  get 'travel' => 'categories#detail', as: :travel
  get 'home-life' => 'categories#detail', as: :home_life
  get 'special-offers' => 'categories#detail', as: :deals
  get 'magazine-issue' => 'categories#detail', as: :themes_articles
  get 'latest-articles' => 'categories#detail', as: :allpost
  get 'commitment' => 'categories#detail', as: :commitment
  get 'contest' => 'categories#detail', as: :contest
  get 'subscribe' => 'page#subscribe', as: :subscribe_now



  get 'advertise' => 'page#advertise', as: :advertise
  get 'about' => 'page#about', as: :about
  get 'contact-us' => 'page#contact', as: :contactus
  get 'njsc-2019-winner' => 'page#njsc_2019_winner', as: :njsc_winner
  get 'promotion' => 'page#promotion', as: :promotion
  get 'privacy-policy' => 'page#privacy', as: :privacy

  post "/add_device" => "devices#add_device", :as => :add_device

  get 'dashboard/index'
  get 'page/index'
  get 'page/about'
  get 'page/advertise'
  get 'page/contact'

  resources :categories do
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  get 'articles/trash/:id' => 'articles#trash', as: :articles_trash
  resources :articles, path: '' do
    collection { post :import }
  end

  get '/categories/:id', to: 'categories#show', as: :dtl_category
  get ':category_name/:sub/', to: 'categories#detail', as: :dtl_sub_category
  get ':category_name/:sub/:id', to: 'articles#show', as: :dtl_article
  get ':category_name/:sub/:id/edit', to: 'articles#edit'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!

  def index
    @total_articles = Article.all.count
    @published_articles = Article.publish.count
    @scheduled_articles = Article.on_scheduled.where.not(:status => 'trash').count
    @total_drafted_articles = Article.drafted.count
    @total_active_banners = Banner.running.count
    @total_subscribe_device = Device.all.count
    if Article.popular.present?
      @most_popular_articles = Article.popular.first.title
    end
    @drafted_articles = Article.drafted
    @articles_on_scheduled = Article.on_scheduled.where.not(status: "draft")
    @expired_banners = Banner.where(expired_date: Date.today..Date.today - 7.day)
    @unread_subscription = Subscribe.where(status:[nil])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => controller_name.titleize %></h4>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <div class="card bg-info">
            <div class="card-body">
              <h4 class="card-title m-b-0 text-white">Articles</h4>
              <h2 class="font-light text-white"><%= @total_articles %></h2>
              <div class="m-t-30">
                <div class="row text-center">
                  <div class="col-4 border-right">
                    <h4 class="m-b-0 text-white"><%= @published_articles %></h4>
                    <a href="#"><span class="font-14 text-white">Published</span></a>
                  </div>
                  <div class="col-4 border-right">
                    <h4 class="m-b-0 text-white"><%= @scheduled_articles %></h4>
                    <a href="#"><span class="font-14 text-white">Scheduled</span></a>
                  </div>
                  <div class="col-4">
                    <h4 class="m-b-0 text-white"><%= @total_drafted_articles %></h4>
                    <a href=""><span class="font-14 text-white">Drafted</span></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card bg-success">
            <div class="card-body">
              <div class="d-flex no-block align-items-center">
                <div class="text-white">
                  <h2><%= @total_active_banners %></h2>
                  <h6><a href="<%= banners_active_path %>">Active Banners</a></h6>
                </div>
                <div class="ml-auto">
                  <span class="text-white display-6"><i class="fa fa-diamond"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card bg-dark">
            <div class="card-body">
              <div class="d-flex no-block align-items-center">
                <div class="text-white">
                  <h2><%= @total_subscribe_device %></h2>
                  <h6>Subsribed Device</h6>
                </div>
                <div class="ml-auto">
                  <span class="text-white display-6"><i class="fa fa-tablet"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title m-b-0">Most Popular Articles</h4>
          <% if @most_popular_articles.present? %>
            <div class="list-group">
              <a href="" class="list-group-item" target="_blank"><%= @most_popular_articles %></a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card" >
        <div class="card-body">
          <h3 class="card-title">Statistics Audience This Month and Last Month</h3>
          <hr>
          <div class="mw-100" style="overflow-x: scroll">
            <iframe width="1181" height="371" seamless frameborder="0" scrolling="no" style="overflow-x:scroll;" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTe3TNZ9DQYezdQoKKNO1MeI_G0v_69_wBNEwxzxs3MdAnXDmU-CRAPGtW0MT_pj0381_PY23vhfJkL/pubchart?oid=1800716902&amp;format=interactive"></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Drafted Articles</h3>
          <hr>
          <div class="table responsive">
            <table class="table table-striped table-hover" id="datablearticle">
              <thead>
                <tr>
                  <th class="text-center">ID</th>
                  <th class="text-center">Title</th>
                  <th class="text-center">Category</th>
                  <th class="text-center">Created At</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @drafted_articles.each_with_index do |x, i| %>
                  <tr>
                    <td class="text-center">
                      <a href="#"><%= x.id %></a>
                    </td>
                    <td class="text-center">
                      <%= x.title  %>
                    </td>
                    <td class="text-center">
                      <strong><%= x.category.title %></strong>
                    </td>
                    <td class="text-center">
                      <%= x.created_at.strftime("%Y/%m/%d@%H:%M") rescue "-" %>
                    </td>
                    <td class="text-center">
                      <a href="<%= article_url(x) %>" class="btn btn-info btn-xs">Preview</a>
                      <a href="<%= edit_article_path(x) %>" class="btn btn-warning btn-xs">Edit</a>
                      <a data-confirm='Are you sure?' class='btn btn-xs btn-danger m-1' rel='nofollow' data-method='delete' href='<%= article_path(x) %>'>Delete</a>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Articles on Schedule</h3>
          <hr>
          <div class="table responsive">
            <table class="table table-striped table-hover" id="datablearticle">
              <thead>
                <tr>
                  <th class="text-center">ID</th>
                  <th class="text-center">Title</th>
                  <th class="text-center">Category</th>
                  <th class="text-center">Publish Date</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @articles_on_scheduled.each_with_index do |x, i| %>
                  <tr>
                    <td class="text-center">
                      <a href="#"><%= x.id %></a>
                    </td>
                    <td class="text-center">
                      <%= x.title  %>
                    </td>
                    <td class="text-center">
                      <strong><%= x.category.title %></strong>
                    </td>
                    <td class="text-center">
                      <%= x.publish.strftime("%Y/%m/%d@%H:%M") rescue "-" %>
                    </td>
                    <td class="text-center">
                      <a href="<%= article_url(x) %>" class="btn btn-info btn-xs">Preview</a>
                      <a href="<%= edit_article_path(x) %>" class="btn btn-warning btn-xs">Edit</a>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Nearly Expired Banners</h3>
          <hr>
          <div class="table responsive">
            <table class="table table-striped table-hover" id="datablebanner">
              <thead>
                <tr>
                  <th class="text-center">No.</th>
                  <th class="text-center">Title</th>
                  <th class="text-center">Position</th>
                  <th class="text-center">Expired Date</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @expired_banners.each_with_index do |x, i| %>
                  <tr>
                    <td class="text-center">
                      <%= i + 1 %>
                    </td>
                    <td class="text-center">
                      <%= x.title %>
                    </td>
                    <td class="text-center">
                      <strong><%= x.position %></strong>
                    </td>
                    <td class="text-center text-danger">
                      <strong><%= x.expired_date %></strong>
                    </td>
                    <td class="text-center">
                      <%= link_to 'Remove',banners_remover_path(id: x.id), data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Unread Subscriptions</h3>
          <hr>
          <div class="table responsive">
            <table class="table table-striped table-hover" id="datablecontact">
              <thead>
                <tr>
                  <th class="text-center">Name</th>
                  <th class="text-center">Package</th>
                  <th class="text-center">Date</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @unread_subscription.each do |x| %>
                  <tr>
                    <td class="text-center">
                      <%= x.title %> <%= x.fullname %>
                    </td>
                    <td class="text-center">
                      <%= x.plan %>
                    </td>
                    <td class="text-center">
                      <%= x.created_at.strftime("%Y/%m/%d@%H:%M") rescue "-" %>
                    </td>
                    <td class="text-center">
                      <a href="<%= subscribe_path(x.id) %>" class="btn btn-info btn-xs">Read</a>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    // $('.table').DataTable();
    $('#datablearticle').DataTable();
    $('#datablebanner').DataTable({
      "pageLength":5,
      "order": []
    });
    $('#datablecontact').DataTable({
      "pageLength":5,
      "order": [[ 2, 'desc' ]]
    });
  } );
</script>