config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :devices
  resources :directories
  resources :image_sliders
  resources :tags
  mount Ckeditor::Engine => '/ckeditor'

  root 'page#index'
  get 'dashboard' => "dashboard#index"

  get 'banners/remover' => 'banners#remover', as: :banners_remover
  get 'banners/article' => 'banners#article', as: :banners_article
  get 'redirect' => 'banners#counter', as: :banners_counter
  get 'send-report-banner' => 'banners#send_report_banner', as: :send_report_banner
  get 'banners/active' => 'banners#active', as: :banners_active
  get 'banners/trash' => 'banners#trash', as: :banners_trash
  resources :banners
  post 'banners/editbanner' => 'banners#editbanner', as: :banners_editbanner
  resources :galleries do
    collection { post :import }
    resources :images, :only => [:create, :destroy]
  end
  resources :videos
  resources :subscribes

  resources :sliders do
    put :sort, on: :collection
  end

  resources :users
  devise_for :users,
  path_names: {
    sign_in: 'digital/login',
    sign_out: 'digital/logout'
  }

  resources :writers do
    collection { post :import }
  end
  resources :contacts

  get 'tagged' => 'page#tagged', as: :tagged_article
  get '/city-updates', to: redirect('/updates', status: 301)
  get '/kids-family', to: redirect('/life/kids-family', status: 301)
  get '/lifestyle', to: redirect('/life', status: 301)
  get '/others', to: redirect('/people', status: 301)
  get '/our-contributors', to: redirect('/about', status: 301)
  get '/soapbox', to: redirect('/people/soapbox', status: 301)
  get '/magazine-issue/money-finance/brikcoin-a-eryptocurrency-for-the-value-of-the-absence-of-plastic', to: redirect('/magazine-issue/money-finance/brikcoin-a-cryptocurrency-for-the-value-of-the-absence-of-plastic', status: 301)
  get '/dining/foodies-corner/ultraviolet-by-paul-piret-multi-sensory-dining-at-its-best', to: redirect('/dining/foodies-corner/ultraviolet-by-paul-pairet-multi-sensory-dining-at-its-best', status: 301)
  get '/art-and-culture/arts/bartega-paint-sip-painting-under-influence', to: redirect('/art-and-culture/arts/bartega-studio-inspiring-creativity-through-social-painting', status: 301)
  get '/dining/culinary-talk/riana-bismaraks-favourite-restaurant', to: redirect('/dining/culinary-talk/5-top-jakarta-restaurants-in-riana-bismaraks-list', status: 301)
  get '/art-and-culture/arts/dedication-chairil-anwar', to: redirect('/art-and-culture/arts/bio-fantasy-melisa-sunjayas-dedication-to-chairil-anwar-bio-fantasy-melisa-sunjayas-dedication-to-chairil-now-jakarta', status: 301)
  get 'search' => 'page#search', as: :search
  get '/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get '/travel/archipelago-diaries/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get 'events/concerts'=> 'events#detail', as: :concerts_events
  get 'events/exhibition'=> 'events#detail', as: :exhibition_events
  get 'events/networking'=> 'events#detail', as: :networking_events
  get 'events/bazaar-and-festival'=> 'events#detail', as: :bazaar_festival_events
  get 'events/seminar-and-workshop'=> 'events#detail', as: :seminar_and_workshop_events
  get 'events/education'=> 'events#detail', as: :education_events
  get 'events/social'=> 'events#detail', as: :social_events
  get 'events/performance'=> 'events#detail', as: :performance_events
  get 'events/competition'=> 'events#detail', as: :competition_events
  get 'events/festive'=> 'events#detail', as: :festive_events
  get 'events/webinar'=> 'events#detail', as: :webinar_events

  get '/city-guides/kota-tua' => 'page#detail_area', as: :detail_area
  get 'latest-articles' => 'page#latest', as: :latest
  get '/list-event' => 'events#index', as: :list_event
  get '/list-article' => 'articles#index', as: :list_article
  get '/export-article' => 'articles#export', as: :export_article
  get '/list-subscriber' => 'subscribes#index', as: :list_subscriber
  get '/events' => 'page#events', as: :all_event

  get '/categories/:id/edit', to: 'categories#edit'
  get '/events/new', to: 'events#new'
  get '/events/:id', to: 'events#show', as: :dtl_event
  get '/events/:id/edit', to: 'events#edit'

  get '/city-guide' => 'categories#detail', as: :city_guide
  get '/photo-stories' => 'page#photos', as: :photos
  get 'dining' => 'categories#detail', as: :dining
  get 'people' => 'categories#detail', as: :people
  get 'art-and-culture' => 'categories#detail', as: :art_and_culture
  get 'life' => 'categories#detail', as: :life
  get 'updates' => 'categories#detail', as: :updates
  get 'events' => 'categories#detail', as: :nearest_event
  get 'business' => 'categories#detail', as: :business
  get 'travel' => 'categories#detail', as: :travel
  get 'home-life' => 'categories#detail', as: :home_life
  get 'special-offers' => 'categories#detail', as: :deals
  get 'magazine-issue' => 'categories#detail', as: :themes_articles
  get 'latest-articles' => 'categories#detail', as: :allpost
  get 'commitment' => 'categories#detail', as: :commitment
  get 'contest' => 'categories#detail', as: :contest
  get 'subscribe' => 'page#subscribe', as: :subscribe_now



  get 'advertise' => 'page#advertise', as: :advertise
  get 'about' => 'page#about', as: :about
  get 'contact-us' => 'page#contact', as: :contactus
  get 'njsc-2019-winner' => 'page#njsc_2019_winner', as: :njsc_winner
  get 'promotion' => 'page#promotion', as: :promotion
  get 'privacy-policy' => 'page#privacy', as: :privacy

  post "/add_device" => "devices#add_device", :as => :add_device

  get 'dashboard/index'
  get 'page/index'
  get 'page/about'
  get 'page/advertise'
  get 'page/contact'

  resources :categories do
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  get 'articles/trash/:id' => 'articles#trash', as: :articles_trash
  resources :articles, path: '' do
    collection { post :import }
  end

  get '/categories/:id', to: 'categories#show', as: :dtl_category
  get ':category_name/:sub/', to: 'categories#detail', as: :dtl_sub_category
  get ':category_name/:sub/:id', to: 'articles#show', as: :dtl_article
  get ':category_name/:sub/:id/edit', to: 'articles#edit'
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  acts_as_taggable_on :tags

  mount_uploader :image, ImageUploader

  belongs_to :writer
  belongs_to :category
  belongs_to :gallery, optional: :true

  Status = [ :publish, :draft, :trash ]

  default_scope { order(publish: :desc) }

  validates :title, presence: true

  class << self

    def on_scheduled
      Article.where("articles.publish >= ?", DateTime.now)
    end

    def publish
      Article.where(status: "publish").where("articles.publish <= ?", DateTime.now).order(publish: :desc)
    end

    def drafted
      Article.where(status: "draft")
    end

    def all_article
        Article.where(status: ["publish","draft"])
    end

    def popular
      Article.where.not(status: 'trash').where.not(status: 'draft').where('publish > ?',30.days.ago).reorder(view_count: :desc)
    end

    def soapbox
      Article.publish.where(category_id: Category.soapbox.id)
    end

    def now_people
      Article.publish.where(category_id: Category.now_people)
    end

    def main_theme
      Article.publish.where(main_theme: true)
    end

    def editor_pick
      Article.publish.where(editor_pick: true).first
    end

    def featured
      Article.publish.where(featured: true)
    end

    def travel
      Article.publish.where(category_id: Category.only_travel)
    end

    def dining
      Article.publish.where(category_id: Category.only_dining)
    end

    def special_offers
      Article.publish.where(category_id: Category.special_offers)
    end

    def art_and_culture
      Article.publish.where(category_id: Category.art_and_culture.children.map(&:id))
    end

    def home_life
      Article.publish.where(category_id: Category.home_life.children.map(&:id))
    end
  end

  def self.search(search)
    where("title ILIKE ? OR meta_des ILIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.in_group(category)
      publish.where(category_id:[ Category.find(category).children.map(&:id)])
  end

  def increase_view!
    self.view_count = self.view_count.to_i + 1
    self.save
  end

  def increase_counter!
    self.wpn_counter = self.wpn_counter.to_i + 1
    self.save
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      if Article.exists?(row["id"])
      else
      new
      params =
      {article:
        {
          id: row["id"],
          title: row["title"],
          meta_title: row["meta_title"],
          meta_des: row["meta_des"],
          content: row["content"],
          publish: row["publish"],
          featured: row["featured"],
          editor_pick: row["editor_pick"],
          category_id: row["category_id"],
          remote_image_url: row["image"],
          slug: row["slug"],
          writer_id: row["writer_id"],
          status: "publish"
        }
       }
        Article.create(params[:article])
      end
      end


    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path,file_warning: :ignore)
      when '.xls' then Roo::Excel.new(file.path,file_warning: :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path,file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :trash]
  before_action :authenticate_user!, :except => [:show]
  layout "admin", :except => [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all_article.first(500)
    if params[:start].present?
      @articles = Article.where(publish: DateTime.parse(params[:start]).beginning_of_day..DateTime.parse(params[:end]).end_of_day)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    if params[:category_name] == nil
      redirect_to dtl_article_path(@article.category.parent.slug, @article.category.slug, @article.slug), status: 301
    end

    if @article.category.parent == nil
      category_name = @article.category.slug
    else
      category_name = @article.category.parent.slug
      sub = @article.category.slug
    end
    # @article.increase_view!
    if params[:source].present?
      if params[:source] == "web-push"
       # @article.increase_counter!
      end
    end
   #  @article.increase_counter!
    @popular = Article.publish.popular.limit(5)
    @related = Article.publish.where.not(id: @article.id).where(category_id:  @article.category_id).limit(5)
    @recent = Article.publish.limit(5)
    if Article.where(content_marketing: true).where("articles.content_marketing_expired <= ?", DateTime.now).count < 1
      @suggested = Article.where(content_marketing: true)
        if @suggested.last.id == @article.id
          @suggested = Article.publish.featured
        end
    else
      @suggested = Article.publish.featured
    end
    prepare_meta_tags(
    title: @article.meta_title,
    description: @article.meta_des,
    image: @article.image,
    twitter: {
      site_name: "NOW JAKARTA | #{@article.meta_title || @article.title}" ,
      site: '@NOW_Jakarta',
      creator: '@NOW_Jakarta',
      card: 'summary',
      description:   @article.meta_des || ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(250),
      title: @article.meta_title || @article.title,
      image: request.protocol + request.host_with_port + @article.image.url
    },
    og: {
      url: request.protocol + request.host_with_port+"/"+ @article.slug,
      site_name:  "NOW JAKARTA | #{@article.meta_title || @article.title}" ,
      title: @article.meta_title || @article.title,
      image: request.protocol + request.host_with_port + @article.image.url,
      type: 'article',
      description:  @article.meta_des || ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(250)
      })
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render :edit, status: :created, location: @article }
        if @article.status == "draft"
          NotifMailer.article(@article).deliver
        end
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if params[:publish].present?
      @article.status = 'publish'
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to edit_article_path(@article), notice: 'Article was successfully updated.' }
          format.json { render :edit, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      @article.status = 'draft'
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to edit_article_path(@article), notice: 'Article was successfully updated.' }
          format.json { render :edit, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def trash
    respond_to do |format|
      if @article.update(:status => 'trash')
        format.html { redirect_to edit_article_path(@article), notice: 'Article was moved to trash.' }
        format.json { render :edit, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    Article.import(params[:file])
    redirect_to articles_path, notice: "Article imported."
  end

  def export
    @articles = Article.first(50)
    if params[:start].present?
      @articles = Article.where(publish: DateTime.parse(params[:start]).beginning_of_day..DateTime.parse(params[:end]).end_of_day)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def article_params
      params.require(:article).permit(:title, :meta_title, :meta_des, :content, :publish, :featured, :editor_pick, :image, :status, :category_id, :writer_id, :slug, :main_theme, :tag_list,:content_marketing,:content_marketing_expired, :slider, :gallery_id, :wpn_counter)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= list_article_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= list_article_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/articles/show.amp.erb
<% if @article.slug == "jakarta-in-a-decade" %>
<%= render :partial => 'custom_content' %>
<% else %>
<section>
  <div class="container">
    <h5 class="category mt-4" >
      <a href="<%= sub_category_url(@article) %>"> <%= @article.category.title %>  </a>| <span class="date"><%= @article.publish.strftime("%e %B %Y") rescue "-" %></span>
    </h5>
    <div class=" position-relative bg-light" style="z-index:10;">
      <h1 class="article-title" style="font-size:30px;line-height:1"><%= @article.title %></h1>
    </div>

    <div class="mt-3 mb-3">

      <div class="d-md-none d-sm-block">

        <p class="heading">
          <amp-social-share type="twitter"
          width="45"
          height="33"></amp-social-share>
          <amp-social-share type="facebook"
          width="45"
          height="33"
          data-attribution="254325784911610"></amp-social-share>
          <amp-social-share type="gplus"
          width="45"
          height="33"></amp-social-share>
          <amp-social-share type="email"
          width="45"
          height="33"></amp-social-share>

        </p>
      </div>
    </div>
    <div class="row justify-content-between">
      <div class="container">
        <div class="article mt-0">
          <%= sanitize @article.content, scrubber: AmpScrubber.new %>
          <div class="mt-5 mb-3">
            <% @article.tag_list.each do |x|  %>
            <a href="<%= search_path(q: x) %>" class="btn btn-dark mb-1 " style="font-size:12px;">#<%= x %></a>
            <% end %>
          </div>
        </div>
        <div class="border-top mb-3 pt-5 " id="author">
          <a href="<%= writer_path(@article.writer.slug) %>">
            <div class="row mt-2 align-items-center">
              <div class="col-3 mb-3">
                <amp-img
                src="<%= @article.writer.image %>"
                width="500"
                height="500"
                layout="responsive"
                alt="<%= @article.writer.fullname %>"
                class="w-100 d-block rounded-circle m-auto"
                >
              </amp-img>
                </div>
                <div class="col-9 ">
                  <h4 class="author-name mb-0"><%= @article.writer.fullname %></h4>
                  <span style="font-weight:100;color:gray">writer</span>
                </div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-12">
          <div class="p-2" style="">
            <div class="">
              <p style="font-family: 'Oswald', sans-serif;font-size: 32px;font-weight: 900;">
                Get Closer To Us
              </p>
              <div class="mb-3">
                <input id="signup_email" name="signup[email]" class="mm-field required email col" type="text" data-required-field="This field is required" placeholder="you@example.com" style="border-bottom:1px solid #000;text-align:left;padding-left:0;font-size:16px;">
              </div>
              <a href="#" class="btn btn-outline-dark w-100">
                SUBMIT
              </a>
            </div>
            </div>
            <div class="mt-2">
              <div class=" text-center pt-3">
                <p class="mb-3" style="font-size:35px;font-weight:900;font-family: 'Cormorant', serif;"><strong>COVID-19</strong> Cases in Indonesia</p>
              </div>
              <div class="  pb-4">
                <div class="row">
                  <div class="col-md-12">
                    <div class="text-center covid-info py-4" style="border-bottom:1px white solid;">
                      <div  class="feed-confirmed">  <p class="count-statistics"><%= @crn_confirm %></p>
                      </div>
                      <p class="mb-0">Confirmed</p>
                    </div>
                  </div>
                  <div class="col-6 pr-0" style="border-right: 1px solid white;">
                    <div class="text-center covid-info py-4  ">
                      <div  class="feed-recovered">  <p class="count-statistics"><%= @crn_cured %></p>
                      </div>
                      <p class="mb-0">Recovered</p>
                    </div>
                  </div>
                  <div class="col-6 pl-0">
                    <div class="text-center covid-info py-4 ">
                      <div  class="feed-deaths">  <p class="count-statistics"><%= @crn_died %></p>
                      </div>
                      <p class="mb-0">Death</p>
                    </div>
                  </div>
                </div>
                <small class="mt-3"><i>API source: <a href="https://covid19api.com" target="_blank"><u><b>https://covid19api.com</b></u></a>. Data Source: <a href="https://systems.jhu.edu/" target="_blank"><u><b>Johns Hopkins CSSE</b></u></a></i></small>
                <p class="mt-3">For live update about Covid-19 cases in Indonesia, visit <a href="http://www.covid19.go.id/situasi-virus-corona" target="_blank"><strong><u>www.covid19.go.id/situasi-virus-corona</u></strong></a>. Get informed, take percautions, and help to contain the virus from spreading.</p>
              </div>
            </div>
            <% @suggested.limit(1).each do |x|  %>
            <div class="mt-4">
              <span class="category" style="margin-bottom:5px;display:block;">
                <a href="<%= sub_category_url(x) %>">Suggested | <%= x.category.title %> </a>
              </span>
              <a href="<%= article_url(x) %>" class="">
                <amp-img
                src="<%= x.image.url(:regular) %>"
                srcset="<%= x.image.url(:regular) %>"
                width="300"
                height="250"
                layout="responsive"
                alt="<%= x.title %>">
              </amp-img>


              <h4 class="title-article mb-1" ><%= x.title %></h4>
              <p class="min-desc">
                <%= x.meta_des %>
              </p>
            </a>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <% end %>

app/views/articles/show.html+phone.erb
<% if @article.slug == "jakarta-in-a-decade" %>
    <%= render :partial => 'custom_content' %>
<% else %>
<section>
  <div class="container">
    <h5 class="category mt-4" >
     <a href="<%= sub_category_url(@article) %>"> <%= @article.category.title %>  </a>| <span class="date"><%= @article.publish.strftime("%e %B %Y") rescue "-" %></span>
    </h5>
    <div class=" position-relative bg-light" style="z-index:10;">
      <h1 class="article-title" style="font-size:30px;line-height:1"><%= @article.title %></h1>
    </div>

      <div class="mt-3 mb-3">

        <div class="d-md-none d-sm-block">

          <ul class="list-inline">
            <!-- <li class="list-inline-item mr-1">
              SHARE:
            </li> -->
            <li class="list-inline-item m-0">
              <a style="font-size:12px;" href="#"  class="btn btn-dark" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=www.nowjakarta.co.id/<%= @article.slug %>','facebook-share-dialog','width=626,height=436');return false;">
                FACEBOOK
              </a>
            </li>
            <li class="list-inline-item m-0">
              <a style="font-size:12px;" target="_blank"  class="btn btn-dark" href="https://twitter.com/intent/tweet?text=<%= @article.title %> , read more at: http://www.nowjakarta.co.id/<%= @article.slug %>">
                TWITTER
              </a>
            </li>
            <li class="list-inline-item m-0">
              <a style="font-size:12px;" target="_blank"  class="btn btn-dark" href="https://wa.me/?text=<%= u "#{@article.title} - http://nowjakarta.co.id/#{@article.slug}" %>">
                WHATSAPP
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row justify-content-between">
        <div class="col-12 mb-3">
          <div class="article mt-0">
            <%= @article.content.html_safe %>
            <div class="mt-5 mb-3">
              <% @article.tag_list.each do |x|  %>
              <a href="<%= search_path(q: x) %>" class="btn btn-dark mb-1 " style="font-size:12px;">#<%= x %></a>
              <% end %>
            </div>
          </div>
          <div class="border-top mb-3 pt-5 " id="author">
            <a href="<%= writer_path(@article.writer.slug) %>">
              <div class="row mt-2 align-items-center">
                <div class="col-3 mb-3">
                  <img src="https://nowjakarta.co.id<%= @article.writer.image %>" alt="<%= @article.writer.fullname %>" class="w-100 d-block rounded-circle m-auto">
                </div>
                <div class="col-9 ">
                  <h4 class="author-name mb-0"><%= @article.writer.fullname %></h4>
                  <span style="color:gray" style="font-weight:100;">writer</span>
                </div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-12">
          <div class="p-2" style="">
            <p style="font-family: 'Oswald', sans-serif;font-size: 32px;font-weight: 900;">
              Get Closer To Us
            </p>
            <button type="button" class="btn  btn-primary  btn-dark" data-toggle="modal" data-target="#subscribeModal">SUBSCRIBE TO OUR NEWSLETTER</button>


            <% Banner.where(category_id: @article.category.parent.id).each do |x| %>
            <div class="banner mb-3 mt-3" >
              <a href="<%= x.link %>">
                <img src="<%= x.image %>" alt="" class="w-100">
              </a>
            </div>
            <% end %>

          </div>

          <% @suggested.limit(1).each do |x|  %>
          <div class="mt-4">
            <span class="category" style="margin-bottom:5px;display:block;">
              <a href="<%= sub_category_url(x) %>">Suggested | <%= x.category.title %> </a>
            </span>
            <a href="<%= article_url(x) %>" class="">
              <img src="<%= x.image.url(:regular) %>" alt="<%= x.title %>" class="w-100 mb-3">
              <h4 class="title-article mb-1" ><%= x.title %></h4>
              <p class="min-desc">
                <%= x.meta_des %>
              </p>
            </a>
          </div>
          <% end %>
          <div class=" mt-4">
            <% Banner.where(category_id: @article.category_id).each do |x| %>
            <div class="banner mb-3" >
              <a href="<%= x.link %>">
                <img src="<%= x.image %>" alt="" class="w-100">
              </a>
            </div>
            <% end %>
          </div>

          <div class="mt-4">
            <h4 style="text-transform:uppercase ;font-family: 'Oswald', sans-serif;font-size: 28px;font-weight: 900;">
              Related Article
            </h4>
            <% @related.limit(5).each do |x| %>
            <a href="<%= article_url(x) %>">
              <div class="d-block">
                <div class="row align-items-center mb-3">
                  <div class="col-4">
                    <img  src="<%= x.image.url(:mobile) %>" alt="<%= x.title %>" class="w-100">
                  </div>
                  <div class="col-8 pl-0">
                    <span class="category" style="display:block;">
                      <%= x.category.title %>
                    </span>
                    <h4 class="title-article"><%= x.title %></h4>
                  </div>
                </div>
              </div>
            </a>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>