config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :devices
  resources :directories
  resources :image_sliders
  resources :tags
  mount Ckeditor::Engine => '/ckeditor'

  root 'page#index'
  get 'dashboard' => "dashboard#index"

  get 'banners/remover' => 'banners#remover', as: :banners_remover
  get 'banners/article' => 'banners#article', as: :banners_article
  get 'redirect' => 'banners#counter', as: :banners_counter
  get 'send-report-banner' => 'banners#send_report_banner', as: :send_report_banner
  get 'banners/active' => 'banners#active', as: :banners_active
  get 'banners/trash' => 'banners#trash', as: :banners_trash
  resources :banners
  post 'banners/editbanner' => 'banners#editbanner', as: :banners_editbanner
  resources :galleries do
    collection { post :import }
    resources :images, :only => [:create, :destroy]
  end
  resources :videos
  resources :subscribes

  resources :sliders do
    put :sort, on: :collection
  end

  resources :users
  devise_for :users,
  path_names: {
    sign_in: 'digital/login',
    sign_out: 'digital/logout'
  }

  resources :writers do
    collection { post :import }
  end
  resources :contacts

  get 'tagged' => 'page#tagged', as: :tagged_article
  get '/city-updates', to: redirect('/updates', status: 301)
  get '/kids-family', to: redirect('/life/kids-family', status: 301)
  get '/lifestyle', to: redirect('/life', status: 301)
  get '/others', to: redirect('/people', status: 301)
  get '/our-contributors', to: redirect('/about', status: 301)
  get '/soapbox', to: redirect('/people/soapbox', status: 301)
  get '/magazine-issue/money-finance/brikcoin-a-eryptocurrency-for-the-value-of-the-absence-of-plastic', to: redirect('/magazine-issue/money-finance/brikcoin-a-cryptocurrency-for-the-value-of-the-absence-of-plastic', status: 301)
  get '/dining/foodies-corner/ultraviolet-by-paul-piret-multi-sensory-dining-at-its-best', to: redirect('/dining/foodies-corner/ultraviolet-by-paul-pairet-multi-sensory-dining-at-its-best', status: 301)
  get '/art-and-culture/arts/bartega-paint-sip-painting-under-influence', to: redirect('/art-and-culture/arts/bartega-studio-inspiring-creativity-through-social-painting', status: 301)
  get '/dining/culinary-talk/riana-bismaraks-favourite-restaurant', to: redirect('/dining/culinary-talk/5-top-jakarta-restaurants-in-riana-bismaraks-list', status: 301)
  get '/art-and-culture/arts/dedication-chairil-anwar', to: redirect('/art-and-culture/arts/bio-fantasy-melisa-sunjayas-dedication-to-chairil-anwar-bio-fantasy-melisa-sunjayas-dedication-to-chairil-now-jakarta', status: 301)
  get 'search' => 'page#search', as: :search
  get '/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get '/travel/archipelago-diaries/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get 'events/concerts'=> 'events#detail', as: :concerts_events
  get 'events/exhibition'=> 'events#detail', as: :exhibition_events
  get 'events/networking'=> 'events#detail', as: :networking_events
  get 'events/bazaar-and-festival'=> 'events#detail', as: :bazaar_festival_events
  get 'events/seminar-and-workshop'=> 'events#detail', as: :seminar_and_workshop_events
  get 'events/education'=> 'events#detail', as: :education_events
  get 'events/social'=> 'events#detail', as: :social_events
  get 'events/performance'=> 'events#detail', as: :performance_events
  get 'events/competition'=> 'events#detail', as: :competition_events
  get 'events/festive'=> 'events#detail', as: :festive_events
  get 'events/webinar'=> 'events#detail', as: :webinar_events

  get '/city-guides/kota-tua' => 'page#detail_area', as: :detail_area
  get 'latest-articles' => 'page#latest', as: :latest
  get '/list-event' => 'events#index', as: :list_event
  get '/list-article' => 'articles#index', as: :list_article
  get '/export-article' => 'articles#export', as: :export_article
  get '/list-subscriber' => 'subscribes#index', as: :list_subscriber
  get '/events' => 'page#events', as: :all_event

  get '/categories/:id/edit', to: 'categories#edit'
  get '/events/new', to: 'events#new'
  get '/events/:id', to: 'events#show', as: :dtl_event
  get '/events/:id/edit', to: 'events#edit'

  get '/city-guide' => 'categories#detail', as: :city_guide
  get '/photo-stories' => 'page#photos', as: :photos
  get 'dining' => 'categories#detail', as: :dining
  get 'people' => 'categories#detail', as: :people
  get 'art-and-culture' => 'categories#detail', as: :art_and_culture
  get 'life' => 'categories#detail', as: :life
  get 'updates' => 'categories#detail', as: :updates
  get 'events' => 'categories#detail', as: :nearest_event
  get 'business' => 'categories#detail', as: :business
  get 'travel' => 'categories#detail', as: :travel
  get 'home-life' => 'categories#detail', as: :home_life
  get 'special-offers' => 'categories#detail', as: :deals
  get 'magazine-issue' => 'categories#detail', as: :themes_articles
  get 'latest-articles' => 'categories#detail', as: :allpost
  get 'commitment' => 'categories#detail', as: :commitment
  get 'contest' => 'categories#detail', as: :contest
  get 'subscribe' => 'page#subscribe', as: :subscribe_now



  get 'advertise' => 'page#advertise', as: :advertise
  get 'about' => 'page#about', as: :about
  get 'contact-us' => 'page#contact', as: :contactus
  get 'njsc-2019-winner' => 'page#njsc_2019_winner', as: :njsc_winner
  get 'promotion' => 'page#promotion', as: :promotion
  get 'privacy-policy' => 'page#privacy', as: :privacy

  post "/add_device" => "devices#add_device", :as => :add_device

  get 'dashboard/index'
  get 'page/index'
  get 'page/about'
  get 'page/advertise'
  get 'page/contact'

  resources :categories do
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  get 'articles/trash/:id' => 'articles#trash', as: :articles_trash
  resources :articles, path: '' do
    collection { post :import }
  end

  get '/categories/:id', to: 'categories#show', as: :dtl_category
  get ':category_name/:sub/', to: 'categories#detail', as: :dtl_sub_category
  get ':category_name/:sub/:id', to: 'articles#show', as: :dtl_article
  get ':category_name/:sub/:id/edit', to: 'articles#edit'
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :youtube_url, :image)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="row">
  <% if @video.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>
<%= form_for @video, :html => { :class => "form-horizontal video" } do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="form-group row">
            <%= f.label :title, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-10">
              <%= f.text_field :title, :class => 'form-control' %>
            </div>
            <%=f.error_span(:title) %>
          </div>
          <div class="form-group row">
            <%= f.label :youtube_url, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-10">
              <%= f.text_field :youtube_url, :class => 'form-control', required: true %>
            </div>
            <%=f.error_span(:youtube_url) %>
          </div>
          <div class="form-group row">
            <%= f.label :image, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-10">
              <%= f.text_field :image, :class => 'form-control' %>
            </div>
            <%=f.error_span(:image) %>
          </div>
          <div class="form-group row">
            <div class="offset-lg-2 col-lg-10">
              <%= f.submit nil, :class => 'btn btn-success' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")), videos_path, :class => 'btn btn-light' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/videos/edit.html.erb
<%- model_class = Video -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= videos_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/videos/index.html.erb
<%- model_class = Video -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_index_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_video_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:title) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:youtube_url) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:image) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @videos.each do |video| %>
                <tr>
                  <td class="text-center"><%= link_to video.id, video_path(video) %></td>
                  <td class="text-center"><%= video.title %></td>
                  <td class="text-center"><%= video.youtube_url %></td>
                  <td class="text-center">
                    <% if video.image.present? %>
                      <img src="<%= video.image.url%>" alt="" width="200px">
                    <% end %>
                  </td>
                  <td class="text-center"><%= video.created_at.strftime("%Y-%m-%d@%H:%M") %></td>
                  <td class="text-center">
                    <%= link_to t('.show', :default => t("helpers.links.show")), video_path(video), :class => 'btn btn-info btn-xs mb-2' %>
                    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_video_path(video), :class => 'btn btn-warning btn-xs mb-2' %>
                    <%= link_to t('.destroy', :default => t("helpers.links.destroy")), video_path(video), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger mb-2' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.table').DataTable();
  } );
</script>

app/views/videos/new.html.erb
<%- model_class = Video -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="<%= videos_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/videos/show.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @video.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:youtube_url) %>:</strong></dt>
  <dd><%= @video.youtube_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @video.image %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              videos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_video_path(@video), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              video_path(@video),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>