config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :devices
  resources :directories
  resources :image_sliders
  resources :tags
  mount Ckeditor::Engine => '/ckeditor'

  root 'page#index'
  get 'dashboard' => "dashboard#index"

  get 'banners/remover' => 'banners#remover', as: :banners_remover
  get 'banners/article' => 'banners#article', as: :banners_article
  get 'redirect' => 'banners#counter', as: :banners_counter
  get 'send-report-banner' => 'banners#send_report_banner', as: :send_report_banner
  get 'banners/active' => 'banners#active', as: :banners_active
  get 'banners/trash' => 'banners#trash', as: :banners_trash
  resources :banners
  post 'banners/editbanner' => 'banners#editbanner', as: :banners_editbanner
  resources :galleries do
    collection { post :import }
    resources :images, :only => [:create, :destroy]
  end
  resources :videos
  resources :subscribes

  resources :sliders do
    put :sort, on: :collection
  end

  resources :users
  devise_for :users,
  path_names: {
    sign_in: 'digital/login',
    sign_out: 'digital/logout'
  }

  resources :writers do
    collection { post :import }
  end
  resources :contacts

  get 'tagged' => 'page#tagged', as: :tagged_article
  get '/city-updates', to: redirect('/updates', status: 301)
  get '/kids-family', to: redirect('/life/kids-family', status: 301)
  get '/lifestyle', to: redirect('/life', status: 301)
  get '/others', to: redirect('/people', status: 301)
  get '/our-contributors', to: redirect('/about', status: 301)
  get '/soapbox', to: redirect('/people/soapbox', status: 301)
  get '/magazine-issue/money-finance/brikcoin-a-eryptocurrency-for-the-value-of-the-absence-of-plastic', to: redirect('/magazine-issue/money-finance/brikcoin-a-cryptocurrency-for-the-value-of-the-absence-of-plastic', status: 301)
  get '/dining/foodies-corner/ultraviolet-by-paul-piret-multi-sensory-dining-at-its-best', to: redirect('/dining/foodies-corner/ultraviolet-by-paul-pairet-multi-sensory-dining-at-its-best', status: 301)
  get '/art-and-culture/arts/bartega-paint-sip-painting-under-influence', to: redirect('/art-and-culture/arts/bartega-studio-inspiring-creativity-through-social-painting', status: 301)
  get '/dining/culinary-talk/riana-bismaraks-favourite-restaurant', to: redirect('/dining/culinary-talk/5-top-jakarta-restaurants-in-riana-bismaraks-list', status: 301)
  get '/art-and-culture/arts/dedication-chairil-anwar', to: redirect('/art-and-culture/arts/bio-fantasy-melisa-sunjayas-dedication-to-chairil-anwar-bio-fantasy-melisa-sunjayas-dedication-to-chairil-now-jakarta', status: 301)
  get 'search' => 'page#search', as: :search
  get '/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get '/travel/archipelago-diaries/refined-dining-experience', to: redirect('/travel/archipelago-diaries/while-in-bali-go-to-these-top-restaurants-for-a-refined-dining-experience', status: 301)
  get 'events/concerts'=> 'events#detail', as: :concerts_events
  get 'events/exhibition'=> 'events#detail', as: :exhibition_events
  get 'events/networking'=> 'events#detail', as: :networking_events
  get 'events/bazaar-and-festival'=> 'events#detail', as: :bazaar_festival_events
  get 'events/seminar-and-workshop'=> 'events#detail', as: :seminar_and_workshop_events
  get 'events/education'=> 'events#detail', as: :education_events
  get 'events/social'=> 'events#detail', as: :social_events
  get 'events/performance'=> 'events#detail', as: :performance_events
  get 'events/competition'=> 'events#detail', as: :competition_events
  get 'events/festive'=> 'events#detail', as: :festive_events
  get 'events/webinar'=> 'events#detail', as: :webinar_events

  get '/city-guides/kota-tua' => 'page#detail_area', as: :detail_area
  get 'latest-articles' => 'page#latest', as: :latest
  get '/list-event' => 'events#index', as: :list_event
  get '/list-article' => 'articles#index', as: :list_article
  get '/export-article' => 'articles#export', as: :export_article
  get '/list-subscriber' => 'subscribes#index', as: :list_subscriber
  get '/events' => 'page#events', as: :all_event

  get '/categories/:id/edit', to: 'categories#edit'
  get '/events/new', to: 'events#new'
  get '/events/:id', to: 'events#show', as: :dtl_event
  get '/events/:id/edit', to: 'events#edit'

  get '/city-guide' => 'categories#detail', as: :city_guide
  get '/photo-stories' => 'page#photos', as: :photos
  get 'dining' => 'categories#detail', as: :dining
  get 'people' => 'categories#detail', as: :people
  get 'art-and-culture' => 'categories#detail', as: :art_and_culture
  get 'life' => 'categories#detail', as: :life
  get 'updates' => 'categories#detail', as: :updates
  get 'events' => 'categories#detail', as: :nearest_event
  get 'business' => 'categories#detail', as: :business
  get 'travel' => 'categories#detail', as: :travel
  get 'home-life' => 'categories#detail', as: :home_life
  get 'special-offers' => 'categories#detail', as: :deals
  get 'magazine-issue' => 'categories#detail', as: :themes_articles
  get 'latest-articles' => 'categories#detail', as: :allpost
  get 'commitment' => 'categories#detail', as: :commitment
  get 'contest' => 'categories#detail', as: :contest
  get 'subscribe' => 'page#subscribe', as: :subscribe_now



  get 'advertise' => 'page#advertise', as: :advertise
  get 'about' => 'page#about', as: :about
  get 'contact-us' => 'page#contact', as: :contactus
  get 'njsc-2019-winner' => 'page#njsc_2019_winner', as: :njsc_winner
  get 'promotion' => 'page#promotion', as: :promotion
  get 'privacy-policy' => 'page#privacy', as: :privacy

  post "/add_device" => "devices#add_device", :as => :add_device

  get 'dashboard/index'
  get 'page/index'
  get 'page/about'
  get 'page/advertise'
  get 'page/contact'

  resources :categories do
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  get 'articles/trash/:id' => 'articles#trash', as: :articles_trash
  resources :articles, path: '' do
    collection { post :import }
  end

  get '/categories/:id', to: 'categories#show', as: :dtl_category
  get ':category_name/:sub/', to: 'categories#detail', as: :dtl_sub_category
  get ':category_name/:sub/:id', to: 'articles#show', as: :dtl_article
  get ':category_name/:sub/:id/edit', to: 'articles#edit'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  mount_uploader :cover, CoverUploader
  friendly_id :title

  has_many :articles
  has_many :events
  has_many :banners

  has_many :children, :class_name => "Category", :foreign_key => :parent_id
  belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id, optional: true



  class << self
    def event
      Category.where(slug: "events-article").first
    end

    def soapbox
      Category.where(slug: "soapbox").first
    end

    def people
      Category.where(slug: "people").first
    end

    def now_people
      Category.where(slug: "now-people").first
    end

    def updates
      Category.where(slug: "updates")
    end

    def dining
      Category.where(slug: "dining").first
    end

    def travel
      Category.where(slug: "travel").first
    end

    def art_and_culture
      Category.where(slug: "art-and-culture").first
    end

    def special_offers
      Category.where(slug: "special-offers").first.children
    end

    def kidsandfamily
      Category.where(slug: "kids-family")
    end

    def lifestyle
        Category.where(slug: "lifestyle")
    end

    def business
      Category.where(slug: "business")
    end

    def magazine_issue
      Category.find("magazine-issue").children
    end

    def home_life
      Category.where(slug: "home-life")
    end

    def parent
      Category.where(parent_id: [nil,""])
    end

    def events
      Category.find(Category.find('events-article').id).children
    end

    def for_articles
      Category.where.not(id: find(Category.find('events-article').id).children.map(&:id)).where.not(id: Category.parent.map(&:id))
    end


  end


  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      if Category.exists?(row["id"])
      else
      new
      params =
      {category:
        {id: row["id"],
          title: row["title"],
          desc: row["desc"],
          parent_id: row["parent_id"]
        }
       }
        Category.create(params[:category])
      end
      end
    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path,file_warning: :ignore)
      when '.xls' then Roo::Excel.new(file.path,file_warning: :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path,file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :detail]
  layout "admin", :except => [:show, :detail]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category.slug = params[:category_name]
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  def detail
    if request.fullpath.split("/")[2] == nil
      @category = Category.find(request.path.delete('/'))
      @first = Article.publish.publish.where.not(id: @first).in_group(@category.id).first
      @articles = Article.publish.publish.where.not(id: @first).in_group(@category.id).page(params[:page]).per(4)
    else
      if params[:page].present?
        @category = Category.find(request.fullpath.split("/")[2].split("?")[0])
      else
        @category = Category.find(request.fullpath.split("/")[2].split("?")[0])
      end

      if Category.magazine_issue.map(&:id).include?(@category.id)
        @articles = Article.publish.publish.where(category_id: @category.id).page(params[:page]).per(4)
      else
        @first = Article.publish.publish.where(category_id: Category.where(slug: @category.slug).first.id).first
        @articles = Article.publish.publish.where.not(id: @first).where(category_id: @category.id).page(params[:page]).per(4)
      end
    end

    if  @category.slug == 'chamber-updates'
      @show_cham = true
    else
      @show_cham = false
    end

    prepare_meta_tags(
      title: @category.title,
      description: @category.desc,
      image: request.protocol + request.host_with_port + Category.magazine_issue.last.cover.url,
      twitter: {
        site_name: "NOW JAKARTA | #{@category.title}" ,
        site: '@NOW_Jakarta',
        creator: '@NOW_Jakarta',
        card: 'summary',
        description: @category.desc,
        title: @category.title,
        image: request.protocol + request.host_with_port + Category.magazine_issue.last.cover.url,
      },
      og: {
        url: request.original_url,
        site_name: "NOW JAKARTA | #{@category.title}" ,
        title:  @category.title,
        image: request.protocol + request.host_with_port + Category.magazine_issue.last.cover.url,
        type: 'article',
        description: @category.desc,
        })


        respond_to do |format|
          format.html
          format.js
        end
      end

      # GET /categories/1/edit
      def edit
      end

      # POST /categories
      # POST /categories.json
      def create
        @category = Category.new(category_params)

        respond_to do |format|
          if @category.save
            format.html { redirect_to @category, notice: 'Category was successfully created.' }
            format.json { render :show, status: :created, location: @category }
          else
            format.html { render :new }
            format.json { render json: @category.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /categories/1
      # PATCH/PUT /categories/1.json
      def update
        respond_to do |format|
          if @category.update(category_params)
            format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
            format.json { render :show, status: :ok, location: @category }
          else
            format.html { render :edit }
            format.json { render json: @category.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /categories/1
      # DELETE /categories/1.json
      def destroy
        @category.destroy
        respond_to do |format|
          format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      def import
        Category.import(params[:file])
        redirect_to categories_path, notice: "Article imported."
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(:title, :desc, :parent_id, :main, :slug, :cover, :month, :year, :emag_link)
      end
    end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_articles.html.erb
<% @articles.each_with_index do |x, i| %>

<div class="col-md-3 ">
  <% unless Category.magazine_issue.map(&:id).include?(x.category_id)%>
  <a href="<%= dtl_sub_category_path(x.category.parent.slug, x.category.slug) rescue dtl_category_path(x.category.slug) %>">
    <span class="category" style="margin-bottom:5px;display:block;"><%= x.category.title %></span>
  </a>
  <% end %>
  <a href="<%= dtl_article_path(x.category.parent.slug, x.category.slug, x.slug) rescue dtl_article_path(x.category.slug, x.category.slug, x.slug) %>">
    <img src="https://nowjakarta.co.id/<%= x.image.url(:regular) %>" alt="<%= x.title %>" class="w-100 mb-3">
    <h3 class="title-article mb-1" ><%= x.title %></h3>
    <p class="min-desc">
      <%= x.meta_des %>
    </p>
  </a>
</div>
<% end %>

app/views/categories/detail.html.erb
<% if   @category.slug == "magazine-issue"  %>
<div class="container mt-1 pb-1 mb-2" >
  <div class=""style="border-bottom: 1px solid black;">
    <div class="row" >
      <div class="col-6">
      </div>
      <div class="col text-right">
        <a href="<%= root_path %>"> <strong> Home</strong></a> / <a href="magazine-issue"> Magazine Issue </a>
      </div>
    </div>
  </div>
</div>
<section>
  <div class="container">
    <div class="heading-section d-md-flex justify-content-between align-items-center text-sm-center">
      <h1>MAGAZINE ISSUES</h1>
    </div>
    <div class="row">
      <% Category.order("created_at desc").where(parent_id: 282).each do |x| %>
      <div class="col-md-3">
        <div class="card mb-3">
          <a href="<%= dtl_sub_category_path(x.parent.slug,  x.slug) %>">
            <img class="card-img-top" src="<%= x.cover %>" alt="<%= x.title %>" class="w-100">
            <div class="card-body" style="background-color:#101010">
              <span class="category text-white" style="font-size:20px;"><%= x.month %> <%= x.year %></span>
              <h3 class="title-article text-white list-section"><%= x.title %></h3>
            </div>
          </a>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

<% elsif Category.magazine_issue.map(&:id).include?(@category.id) %>
<div class="container mt-1 pb-1 mb-2" >
  <div class=""style="border-bottom: 1px solid black;">
    <div class="row" >
      <div class="col text-right">
        <a href="<%= root_path %>"> <strong> Home</strong></a> / <a href="magazine-issue"> <strong>Magazine Issue</strong> </a> / <a href="<%= @category.slug %>"> <%= @category.title %></a>
      </div>
    </div>
  </div>
</div>
<section class="infinite-table">
  <div class="container">
    <div class="row" id="first-article">
      <div class="col-md-6 xx">
        <div class="w-75">
          <img src="<%= @category.cover %>" alt="" class="w-100">
        </div>

      </div>
      <div class="col-md-6 xx" style="display:flex;align-items:center">
        <div class="" style="">
          <div class="post-title">

            <span class="category"><%=  @category.month %> issue</span>

            <h4 class="title-article" style="font-size:35px"><%= @category.title %></h4>
            <p class="min-desc">
              <%= @category.desc %>
            </p>

          </div>
        </div>
      </div>
    </div>
    <hr style="margin-top:30px;">
    <div class="">
      <div class="row  mb-30" id="all">
        <%= render "categories/articles" %>
      </div>
      <div class="text-center btn-load-more">
        <a id="load_more" class="btn btn-outline-dark" rel="next" data-remote="true" href="<%= request.path %>?page=<%= @articles.current_page+1 %>">LOAD MORE</a>
      </div>
    </div>

  </div>
</section>

<% elsif Category.parent.include?(@category) %>
<div class="container">
  <%= ctr_banner_long("ctrtop") %>
</div>

<div class="container mt-1 pb-1 mb-2" >

  <div class=""style="border-bottom: 1px solid black;">
    <div class="row" >
      <div class="col text-right pt-2 pb-2">
        <a href="<%= root_path %>">Home</a> / <a href="<%= @category.slug %>"> <strong><%= @category.title.titleize %></strong></a>
      </div>
    </div>
  </div>

  <div class="">

  </div>
</div>
<section class="infinite-table d-flex">
  <div class="pl-3 " style="width:10%">
    <div class="sticky-top">
      <%= ctr_banner_long("ctrleft") %>
    </div>
  </div>
  <div class="container">
    <div class="heading-section">
      <div class="row align-items-center">
        <div class="" style="padding-left:15px;width:fit-content !important">
          <h1><%= @category.title %></h1>
        </div>
        <div class="col">
          <ul class="nav nav-event-category d-none d-md-block">
            <% @category.children.each do |x| %>
            <% unless x.slug == "note-from-editors" %>
            <li class="nav-item ">
              <h2 style="font-weight:300;font-family: 'heebo', sans-serif;" class="mb-0"><a class="nav-link p-0 pr-4 active" style="text-transform:uppercase" href="<%= dtl_sub_category_path(x.parent.slug,  x.slug) %>"><%= x.title %></a></h2>
            </li>
            <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="row align-items-center" id="first-article">
      <div class="col-md-6 xx">
        <a href="<%= article_url(@first)  %>">
          <img src="https://nowjakarta.co.id/<%= @first.image.url(:featured)  rescue "-"%>" alt="" class="w-100">
        </a>
      </div>
      <div class="col-md-6 xx" style="display:flex;align-items:center">
        <div class="" style="">
          <div class="post-title">
            <a href="<%= sub_category_url(@first) %>">
              <span class="category"><%= @first.category.title %></span>
            </a>
            <a href="<%= article_url(@first)  %>">
              <h3 class="title-article" style="font-size:35px"><%= @first.title %></h3>
              <p class="min-desc">
                <%= @first.meta_des %>
              </p>
            </a>
          </div>
          <div class="">
            <span style="font-size:10px;color:grey;text-transform:uppercase;font-weight:700;">
              <%= @first.writer.fullname %>
            </span>
          </div>
        </div>
      </div>

    </div>
    <hr style="margin-top:30px;">
    <div class="">
      <div class="row  mb-30" id="all">
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Display Horizontal -->
        <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-4080030071889451"
        data-ad-slot="6974836536"
        data-ad-format="auto"
        data-full-width-responsive="true"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        <%= render "categories/articles" %>
      </div>
      <div class="text-center btn-load-more">
        <a id="load_more" class="btn btn-outline-dark" rel="next" data-remote="true" href="<%= request.path %>?page=<%= @articles.current_page+1 %>">LOAD MORE</a>
      </div>
    </div>

  </div>
  <div class="pr-3 " style="width:10%">
    <div class="sticky-top">
      <%= ctr_banner_long("ctrright") %>
    </div>
  </div>
</section>
<% else %>
<div class="container mt-1 pb-1 mb-2" >
  <div class=""style="border-bottom: 1px solid black;">
    <div class="row" >
      <div class="col text-right pt-2 pb-2">
        <a href="<%= root_path %>">Home</a> / <a href="/<%= @category.parent.slug %>"><%= @category.parent.title %></a> / <a href="<%= @category.slug %>"> <strong> <%= @category.title.titleize %> </strong></a>
      </div>
    </div>
  </div>
</div>
<% if @show_cham == true %>
<div class="container">
  <div class="text-center">
    <h3 style="font-size: 27px;font-weight: 300;margin: 40px 0;">
      In this section, NOW! Jakarta proudly supports these chambers of commerce:
    </h3>
  </div>
  <div class="w-75 m-auto text-center">
    <div class="pt-3 pb-3">
      <div class="row align-items-end">
        <div class="col text-center">
          <a href="https://www.amcham.or.id/en/home" target="_blank">
            <img src="<%= asset_url('chamber/amchan.png') %>" alt="AMCHAM" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">AMCHAM</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="http://dancham.id/" target="_blank">
            <img src="<%= asset_url('chamber/dancham.png') %>" alt="DANCHAM" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">DANCHAM</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="http://www.britcham.or.id/" target="_blank">
            <img src="<%= asset_url('chamber/britcham.png') %>" alt="BRITCHAM" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">BRITCHAM</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="https://indonesien.ahk.de/en/" target="_blank">
            <img src="<%= asset_url('chamber/EKONID.png') %>" alt="EKONID" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">EKONID</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="http://www.iabc.or.id/" target="_blank">
            <img src="<%= asset_url('chamber/iabc.png') %>" alt="IABC" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">IABC</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="https://www.ifcci.org.in/" target="_blank">
            <img src="<%= asset_url('chamber/ifcci.jpg') %>" alt="IFCCI" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">IFCCI</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="http://www.iccc.or.id/" target="_blank">
            <img src="<%= asset_url('chamber/icccc.png') %>" alt="ICCC" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:300">ICCC</h4>
          </a>
        </div>
        <div class="col text-center">
          <a href="http://www.eurocham.id/" target="_blank">
            <img src="<%= asset_url('chamber/EuroCham.jpg') %>" alt="EuroCham" class="w-100 mb-3">
            <h4 style="font-size:14px;font-weight:500">EuroCham</h4>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="container">
  <%= ctr_banner_long("ctrtop") %>
</div>

<section class="infinite-table d-flex">
  <div class="pl-3" style="width:10%">
    <%= ctr_banner_long("ctrleft") %>
  </div>
  <div class="container">
    <div class="heading-section d-md-flex justify-content-between align-items-center text-sm-center">
      <h1><%= @category.title %></h1>
    </div>
    <div class="row" id="first-article">
      <div class="col-md-6 xx">
        <a href="<%= article_url(@first)  %>">
          <img src="<%= @first.image.url(:featured) %>" alt="" class="w-100">
        </a>
      </div>
      <div class="col-md-6 xx" style="display:flex;align-items:center">
        <div class="" style="">
          <div class="post-title">
            <a href="<%= sub_category_url(@first) %>">
              <span class="category"><%= @first.category.title %></span>
            </a>
            <a href="<%= article_url(@first)  %>">
              <h3 class="title-article" style="font-size:35px"><%= @first.title %></h3>
              <p class="min-desc">
                <%= @first.meta_des %>
              </p>
            </a>
          </div>
          <div class="">
            <span style="font-size:10px;color:grey;text-transform:uppercase;font-weight:700;">
              <%= @first.writer.fullname %>
            </span>
          </div>
        </div>
      </div>
    </div>
    <hr style="margin-top:30px;">
    <div class="">
      <div class="row  mb-30" id="all">
        <%= render "categories/articles" %>
      </div>
      <div class="text-center btn-load-more">
        <a id="load_more" class="btn btn-outline-dark" rel="next" data-remote="true" href="<%= request.path %>?page=<%= @articles.current_page+1 %>">LOAD MORE</a>
      </div>
    </div>

  </div>
  <div class="pr-3" style="width:10%">
    <%= ctr_banner_long("ctrright") %>
  </div>
</section>


<% end %>

app/views/categories/detail.js.erb
// Append new data
$("<%=j render(:partial => 'articles', :object => @articles) %>")
  .appendTo($("#all"));

// Update pagination link
<% if @articles.last_page? %>
  $('.btn-load-more').html("That's all, folks!");
<% else %>
  $('#load_more').replaceWith("<a id='load_more' class='btn btn-outline-dark' rel='next' data-remote='true' href='<%= request.path %>?page=<%= @articles.current_page+1 %>'>LOAD MORE</a>");
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>